version: "3.7"
services:
  web:
    build: ""
    command: python manager.py
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=cursor
      - POSTGRES_PASSWORD=very_secret_password
      - POSTGRES_DB=cursor_sqlalchemy_db
    expose:
      - 5432
    ports:
      - "5432:5432"